### ISSUE TITLE
TOC showing up at end of created eBook

### ISSUE THREAD

**Issue by DawsonG** [Grandt/PHPePub#25]
This maybe something I'm doing wrong, but I can't seem to figure it out.  I'm using the following code to create a new epub file.  I need to add the Table of Contents after the cover page but before the rest of the book.  Instead I'm getting the whole book THEN the TOC.

Can you help?  Thanks.

```
function epub_generate_rss($blogurl, $authorname = false) {
    $book = new EPub();
    $book->setTitle("test");
    if (!$authorname)
        $authorname = "Ima Author";

    $book->setAuthor($authorname, $authorname);
    $book->setIdentifier($blogurl . "&stamp=" . time(), EPub::IDENTIFIER_URI); 
    $book->setLanguage("en");

    $book->addCSSFile("styles.css", "css1", $epub_css);
    $cover = $epub_content_start . "<h1>" . $feed->get_title() . "</h1>\n";
    if ($authorname)
        $cover .= "<h2>By: $authorname</h2>\n";
    $cover .= "<h2>From: <a href=\"$blogurl\">$blogurl</a></h2>";
    $cover .= $epub_content_end;
    $book->addChapter("Notices", "Cover.html", $cover);
    $book->buildTOC();

        $book->addChapter(
           "Test", 
            "Chapter1.html", 
            $epub_content_start . "<h1Test Title</h1>\nPlenty of test content" . $epub_content_end
        );
    }

    return $book;
}
```

**Comment by Grandt** [comment]
I think I found the error. I just committed a fix to the 4.0.0 branch

**Comment by waylaidwanderer** [comment]
I had the opportunity to test this just now, and the problem is unfortunately still happening.

Here's an example of a generated file: https://dl.dropboxusercontent.com/u/10793087/Black-Magic-Lunatic-Howling-in-the-Night.epub

**Comment by bogdangainusa** [comment]
Did someone managed to add TOC after first page and not at the end of document?

**Comment by hatmandu** [comment]
I have the same problem - it's a real shame as this stops the epub files from validating properly with epubcheck. Any ideas?

**Comment by wohoksolutions** [comment]
Found a solution for that - had the problem myself. Set the following:

`$book->isReferencesAddedToToc = false;`
